add FromStr method for EmailAddress
Sayan751/email-address-parser pull request #11
Opened 2023-05-28 11:37 UTC by techhazard

This allows `EmailAddress` to be used with `clap`, the commandline argument parser.

FromStr is just wrapping around the existing `EmailAddress::parse` method, using the default options (`is_lax = false` at time of writing).

2023-05-28 11:44 UTC, techhazard commented
Force push was to remove a rustfmt change that was unrelated to this PR.

2023-05-30 15:35 UTC, Sayan751 requested changes

2023-05-31 09:42 UTC, techhazard commented on rust-lib/src/email_address.rs
I've added a test example in the docstring. Do you need more extensive testing?

2023-05-31 17:48 UTC, merged

2023-06-03 19:16 UTC, techhazard commented
🎉